using System;
using System.Collections.Generic;

namespace Problem2
{
    /// <summary>
    /// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
    /// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    /// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
    /// </summary>
    class Program
    {
        static List<int> fibonacci = new List<int>();
        static void Main(string[] args)
        {
            fibonacci.Add(1);
            fibonacci.Add(2);

            int i = 1;
            int val = 2;
            int result = 2;
            while (true)
            {
                val = fibonacci[i] + fibonacci[i - 1];
                if (val > 4000000)
                {
                    break;
                }
 
                fibonacci.Add(val);

                if (val % 2 == 0)
                {
                    result += val;
                }
                i++;

                Console.Write(val + ",");
            }

            Console.Write(result);
            // 4613732
        }
    }
}
